name: Deployment Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

env:
  CONDITION: ${{ contains(github.event.head_commit.message, '#skip') }}

jobs:
  simple-deployment-pipeline:
    runs-on: ubuntu-latest
    outputs:
      condition: ${{ env.CONDITION }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run tests
        run: npm run test
      - name: Trigger deployment
        if: github.event_name == 'push' && env.CONDITION == 'false'
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple-deployment-pipeline]
    runs-on: ubuntu-latest
    if: ${{ needs.simple-deployment-pipeline.outputs.condition == 'false' }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: github.event_name == 'push'
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch