name: Deployment Pipeline

on:
  push:
    branches: [ main ]

jobs:
  simple-deployment-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setuop-node@v4
      with:
          node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Check style
      run: npm run eslint
	